### ISSUE TITLE
The CJS build of Vite's Node API is deprecated

### ISSUE THREAD

**Issue by jiadesen** [emosheeep/vite-plugin-virtual-mpa#63]
vite@5.1.3
vite-plugin-virtual-mpa@1.10.0

```
Trace: The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
    at warnCjsUsage (/Users/xxx/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_terser@5.27.1/node_modules/vite/index.cjs:32:3)
    at Object.<anonymous> (/Users/xxx/node_modules/.pnpm/vite@5.1.3_@types+node@20.11.19_less@4.2.0_terser@5.27.1/node_modules/vite/index.cjs:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/Users/xxx/node_modules/.pnpm/vite-plugin-virtual-mpa@1.10.0_postcss@8.4.35_typescript@5.3.3_vite@5.1.3/node_modules/vite-plugin-virtual-mpa/dist/index.js:88:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
```

<img width="567" alt="image" src="https://github.com/emosheeep/vite-plugin-virtual-mpa/assets/22772994/2218efda-5123-4467-b130-dc9ce6a6796a">

**Comment by emosheeep** [comment]
This is resolved by https://github.com/emosheeep/vite-plugin-virtual-mpa/pull/62, but I haven't published.

**Comment by emosheeep** [comment]
v1.10.1 has published.
